version: "3.9"
networks:
  services-net:
    name: services-net
services:
  # Tunnelbroker optimized release
  tunnelbroker-server:
    build:
      dockerfile: tunnelbroker/Dockerfile
      context: .
      args:
        - BUILD_TYPE=Release
    image: commapp/tunnelbroker-server:0.3
    container_name: tunnelbroker-server
    ports:
      - "${COMM_SERVICES_PORT_TUNNELBROKER}:50051"
    volumes:
      - $HOME/.aws/config:/root/.aws/config:ro
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./tunnelbroker/tunnelbroker.ini:/opt/tunnelbroker/tunnelbroker.ini:ro
  # Tunnelbroker dev environment
  tunnelbroker-server-dev:
    depends_on:
      - "localstack"
      - "rabbitmq"
    build:
      dockerfile: tunnelbroker/Dockerfile
      context: .
      args:
        - BUILD_TYPE=Debug
    image: commapp/tunnelbroker-server-dev:0.3
    container_name: tunnelbroker-server-dev
    ports:
      - "${COMM_SERVICES_PORT_TUNNELBROKER}:50051"
    volumes:
      - $HOME/.aws/config:/root/.aws/config:ro
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./tunnelbroker/tunnelbroker.ini:/opt/tunnelbroker/tunnelbroker.ini:ro
  # Localstack for s3 and dynamoDB dev environment
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  # RabbitMQ local instance for AMQP dev environment
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - services-net
